apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-worker
  labels:
    app: stripe-worker
spec:
  selector:
    matchLabels:
      app: stripe-worker
  template:
    metadata:
      labels:
        app: stripe-worker
    spec:
      containers:
        - name: stripe-worker
          image: temporal-workers
          command: [ "java" ]
          args: [ "-cp", "/app/workers.jar", "me.mprieto.temporal.workers.StripeWorker", "$(TEMPORAL_HOST):$(TEMPORAL_PORT)" ]
          env:
            - name: STRIPE_API_KEY
              value: "$(STRIPE_API_KEY)"
