apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-workflow-worker
  labels:
    app: checkout-workflow-worker
spec:
  selector:
    matchLabels:
      app: checkout-workflow-worker
  template:
    metadata:
      labels:
        app: checkout-workflow-worker
    spec:
      containers:
        - name: checkout-workflow-worker
          image: temporal-workers
          command: [ "java" ]
          args: [ "-cp", "/app/workers.jar", "me.mprieto.temporal.workers.CheckoutWorkflowWorker", "$(TEMPORAL_HOST):$(TEMPORAL_PORT)" ]