apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-checkout-workflow
  labels:
    app: worker-checkout-workflow
spec:
  selector:
    matchLabels:
      app: worker-checkout-workflow
  template:
    metadata:
      labels:
        app: worker-checkout-workflow
    spec:
      containers:
        - name: worker-checkout-workflow
          image: worker-checkout-workflow
          command: [ "java" ]
          env:
            - name: TEMPORAL_TARGET
              value: {{ .Values.temporal.target | quote }}
          args: [ "-cp", "/app/workflow-worker.jar", "me.mprieto.temporal.checkout.Worker", "$(TEMPORAL_TARGET)" ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-session-activity
  labels:
    app: worker-session-activity
spec:
  selector:
    matchLabels:
      app: worker-session-activity
  template:
    metadata:
      labels:
        app: worker-session-activity
    spec:
      containers:
        - name: worker-session-activity
          image: worker-session-activity
          command: [ "java" ]
          env:
            - name: TEMPORAL_TARGET
              value: {{ .Values.temporal.target | quote }}
          args: [ "-cp", "/app/session-worker.jar", "me.mprieto.temporal.session.Worker", "$(TEMPORAL_TARGET)" ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-stripe-activity
  labels:
    app: worker-stripe-activity
spec:
  selector:
    matchLabels:
      app: worker-stripe-activity
  template:
    metadata:
      labels:
        app: worker-stripe-activity
    spec:
      containers:
        - name: worker-stripe-activity
          image: worker-stripe-activity
          env:
            - name: STRIPE_API_KEY
              value: {{ .Values.stripe.apiKey | quote }}
            - name: TEMPORAL_TARGET
              value: {{ .Values.temporal.target | quote }}
          command: [ "java" ]
          args: [ "-cp", "/app/stripe-worker.jar", "me.mprieto.temporal.stripe.Worker", "$(TEMPORAL_TARGET)", "$(STRIPE_API_KEY)" ]