apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-checkout-workflow
  labels:
    app: worker-checkout-workflow
spec:
  selector:
    matchLabels:
      app: worker-checkout-workflow
  template:
    metadata:
      labels:
        app: worker-checkout-workflow
    spec:
      containers:
        - name: worker-checkout-workflow
          image: worker-checkout-workflow
          command: [ "java" ]
          env:
            - name: TEMPORAL_TARGET
              value: {{ .Values.temporal.target | quote }}
          args: [ "-cp", "/app/workflow-worker.jar", "me.mprieto.temporal.checkout.Worker", "$(TEMPORAL_TARGET)" ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-session-activity
  labels:
    app: worker-session-activity
spec:
  selector:
    matchLabels:
      app: worker-session-activity
  template:
    metadata:
      labels:
        app: worker-session-activity
    spec:
      containers:
        - name: worker-session-activity
          image: worker-session-activity
          command: [ "java" ]
          env:
            - name: TEMPORAL_TARGET
              value: {{ .Values.temporal.target | quote }}
            - name: BASE_URL
              value: {{ .Values.sessions.baseUrl | quote }}
          args: [ "-cp", "/app/session-worker.jar", "me.mprieto.temporal.session.Worker", "$(TEMPORAL_TARGET)", "$(BASE_URL)" ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-stripe-activity
  labels:
    app: worker-stripe-activity
spec:
  selector:
    matchLabels:
      app: worker-stripe-activity
  template:
    metadata:
      labels:
        app: worker-stripe-activity
    spec:
      containers:
        - name: worker-stripe-activity
          image: worker-stripe-activity
          env:
            - name: TEMPORAL_TARGET
              value: {{ .Values.temporal.target | quote }}
            - name: STRIPE_API_KEY
              value: {{ .Values.stripe.apiKey | quote }}
          command: [ "java" ]
          args: [ "-cp", "/app/stripe-worker.jar", "me.mprieto.temporal.stripe.Worker", "$(TEMPORAL_TARGET)", "$(STRIPE_API_KEY)" ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mailgun-activity
  labels:
    app: worker-mailgun-activity
spec:
  selector:
    matchLabels:
      app: worker-mailgun-activity
  template:
    metadata:
      labels:
        app: worker-mailgun-activity
    spec:
      containers:
        - name: worker-mailgun-activity
          image: worker-mailgun-activity
          env:
            - name: TEMPORAL_TARGET
              value: {{ .Values.temporal.target | quote }}
            - name: BASE_URL
              value: {{ .Values.mailgun.baseUrl | quote }}
            - name: USER
              value: {{ .Values.mailgun.user | quote }}
            - name: API_KEY
              value: {{ .Values.mailgun.apiKey | quote }}
            - name: FROM
              value: {{ .Values.mailgun.from | quote }}
            - name: SPLIT_IO_API_TOKEN
              value: {{ .Values.split.apiToken | quote }}
          command: [ "java" ]
          args: [ "-cp",
                  "/app/mailgun-worker.jar",
                  "me.mprieto.temporal.mailgun.Worker",
                  "$(TEMPORAL_TARGET)",
                  "$(BASE_URL)",
                  "$(USER)",
                  "$(API_KEY)",
                  "$(FROM)",
                  "$(SPLIT_IO_API_TOKEN)"]
